### ISSUE TITLE
Loading coadd catalog raises `NoSuchNodeError`

### ISSUE THREAD

**Issue by djperrefort** [djperrefort/gcr-catalogs#1]
Trying to load the coadd data using the GCR raises an error when parsing `merged_tract_4850.hdf5`. The file is missing the child `coadd_4850_41.block4_items`. This can be reproduced by running:

    import sys

    sys.path.insert(1, '/global/common/software/lsst/common/miniconda/current/lib/python3.6/site-packages')

    import GCRCatalogs

    # Check you are using the checked out repo, and not the global installation
    print(GCRCatalogs.__file__)

    gc = GCRCatalogs.load_catalog('coadd')
    print(sorted(gc.list_all_quantities()))
    gc.get_quantities(['dec'])

Which yields:

    NoSuchNodeError: group ``/coadd_4850_41`` does not have a child named ``block4_items``

Checking the file directly also verify the missing child:

    import tables
    path = '/global/projecta/projectdirs/lsst/global/in2p3/Run1.1/summary/merged_tract_4850.hdf5'
    data_table = tables.open_file(path, 'r')
    print(repr(data_table.root.coadd_4850_41))

I've randomly sampled a few of the other files / groups and they all have the `block4_items` child. I can skip loading this particular group, but I'm hesitant without an explanation for the missing child. 

@wmwv any thoughts on why there might be a missing child?

**Comment by wmwv** [comment]
@djperrefort I don't have any specific ideas.  That merged_tract file was created in the middle of severl others.  I don't have any reason to suspect it.

**Comment by djperrefort** [comment]
In that case I’ll have the reader skip the group with a warning. Thank you.

**Comment by wmwv** [comment]
Could you provide me full instructions to recreate?  The ones above just import the GCRCatalogs module in the system path that you've picked up above.  I presume that I should be using a branch from your fork of this repo?

Why do you have the `sys.path.insert` in any case?  Just loading the LSST/DESC suite on Cori will provide that directory (or the moral equivalent).

**Comment by wmwv** [comment]
Where's the part that includes the `dc2_static_coadd_reader.py` from `DC2_Repo/scripts/reader`?

**Comment by djperrefort** [comment]
### Why do you have the sys.path.insert in any case? 

The `sys.path.insert` is left over from copy-pasting a code snippets in Yao's GCR tutorial. I've inserted the global packages as the second list entry so that any local version of `GCRCatalogs` will be imported before the current global version.

### Could you provide me full instructions to recreate? 

To fully reproduce, first clone the `coadd_reader` branch:

    git clone https://github.com/djperrefort/gcr-catalogs -b coadd_reader

Working from the same directory you just ran the above command, the following python code should raise the `NoSuchNodeError`:

    import sys

    sys.path.insert(1, '/global/common/software/lsst/common/miniconda/current/lib/python3.6/site-packages')

    import GCRCatalogs

    # Check you are using the checked out repo, and not the global installation
    print(GCRCatalogs.__file__)

    gc = GCRCatalogs.load_catalog('dc2_static_coadd')
    print(sorted(gc.list_all_quantities()))
    gc.get_quantities(['dec'])

This example has been updated from previous one to reflect a renaming of the catalog reader that happened earlier today.

### Where's the part that includes the dc2_static_coadd_reader.py from DC2_Repo/scripts/reader?

The coadd reader can be found in `GCRCatalogs/dc2_static_coadd.py`. The config file for this reader is located in `GCRCatalogs/catalog_configs/dc2_static_coadd.yaml`. When the package initializes it iterates over the config files, which point to each individual catalog reader. The specific code for this can be found in `GCRCatalogs/register.py`.

**Comment by wmwv** [comment]
Thanks, the `coadd_reader` branch wasn't present previously which is why I asked all those questions.

**Comment by wmwv** [comment]
@djperrefort Do you see the same error messages when using the example notebook in `DC2_Repo/Notebooks/DC2 Static Coadd Catalog reader`?

**Comment by djperrefort** [comment]
yes. Using the demo notebook in `DC2_repo` and changing the demo to use tract number 4850  instead of 4637  yields the same error.
